# Generated by Django 5.2.6 on 2025-09-15 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('mr_no', models.CharField(max_length=100, unique=True)),
                ('age', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('admission_date', models.CharField(max_length=50)),
                ('operation_date', models.CharField(max_length=50)),
                ('discharge_date', models.CharField(max_length=50)),
                ('comorbid', models.TextField()),
                ('presenting_complain', models.TextField()),
                ('examination', models.TextField()),
                ('hand_written_diagnosis', models.TextField()),
                ('classification', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('procedure', models.TextField()),
                ('operative', models.CharField(max_length=100)),
                ('surgeon_name', models.CharField(max_length=255)),
                ('pre_op_neurology', models.TextField()),
                ('surgery', models.CharField(max_length=100)),
                ('side', models.CharField(max_length=50)),
                ('spine_level', models.CharField(max_length=100)),
                ('mri_findings', models.TextField()),
                ('instrumentation', models.TextField()),
                ('mri', models.CharField(max_length=100)),
                ('after_complication', models.TextField()),
                ('re_do_surgery', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
